version: '3'

services:
  postgresdb:
    image: postgres:9.6
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-network

  nodejs-app:
    build:
      context: ./back-end
      dockerfile: dockerfile
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - ./back-end/:/back-end/
      - /back-end/node_modules
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  data:
  pgadmin-data:

networks:
  app-network: